sudo: false
language: go
# https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance
go:
  - 1.7
  - 1.8
  - 1.x
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -v github.com/mattn/goveralls
  - go get -v github.com/go-playground/overalls
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - overalls -project github.com/nochso/bytesort -covermode count -- -race -v
  - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci
